### ISSUE TITLE
 compilation.templatesPlugin is not a function 

### ISSUE THREAD

**Issue by 442627268** [ly525/luban-h5#101]
用npm install后 npm run serve启动报如下错误
![image](https://user-images.githubusercontent.com/19165995/68170139-91ab7680-ffa9-11e9-80fe-5a3749c60541.png)
的解决方案如下：
1.删除node_modules 用cnpm安装是一种解决方法。
2.删除node_modules 用npm add webpack@latest安装依赖也能启动。
原因是：因为你的webpack不是最新版本,但是install去下载也不是最新,所以这里我们要手动下载

**Comment by ly525** [comment]
我们为何不推荐使用npm 或 cnpm 的原因参见 #92，因为我们使用了 yarn.lock 来保证安装依赖的一致性。以及部署在heroku 上的时候，其文档提及只能拥有一个lock 文件，我们也有考虑到这方面的兼容问题

另外，我们发现可以使用 preinstall 来检查用户使用的是 npm 还是 yarn，从而做更好的包管理。

当然如果你可以用cnpm 解决也是可以的。
