### ISSUE TITLE
strapi,换成了product模式，管理后台Admin panel 就进不去了

### ISSUE THREAD

**Issue by weiccTest** [ly525/luban-h5#102]
![image](https://user-images.githubusercontent.com/7098301/68637961-144cac80-053b-11ea-9937-cbe930a4eb59.png)
访问
http://localhost/admin
跳转到首面

**Comment by ly525** [comment]
这里的 strapi 切换成 `production 模式` 是指？改了什么配置文件吗？

**Comment by ly525** [comment]
strapi 在生产环境部署，需要先编译 admin，因为它也是一个前端项目

**Comment by ly525** [comment]
参见 #103 以及strapi deployment 文档
