### ISSUE TITLE
前后端分离接口403

### ISSUE THREAD

**Issue by Gumplefik** [ly525/luban-h5#103]
### 前后端分离后静态页面访问api 403
api使用docker + pm2部署
```
{
  "name": "h5-platform-api",
  "script": "node server.js", 
  "cwd": "/app", 
  "watch": [ 
    "bin",
    "routers"
  ],
  "ignore_watch": [ 
    "node_modules",
    "logs",
    "public"
  ],
  "watch_options": {
    "followSymlinks": false
  },
  "error_file": "/var/log/app-err.log",
  "out_file": "/var/log/app-out.log",
  "env": {
    "NODE_ENV": "production",
    "PORT": 80
  }
}
```
api无法进入/admin设置权限，/admin路径访问无效，返回统一静态页面
![image](https://user-images.githubusercontent.com/19474332/68638597-0ac44400-053d-11ea-9118-a36f605ab468.png)

期望：前后端分离后，访问api可以调通

**Comment by ly525** [comment]
@Gumplefik 方便提供 dockerfile，我这边无法复线这个问题。
或者提供一段视频，来做演示

**Comment by Gumplefik** [comment]
> @Gumplefik 方便提供 dockerfile，我这边无法复线这个问题。
> 或者提供一段视频，来做演示
问题解决了：
其实是strapi必须在构建镜像时npm run build一下编译出admin的静态文件,基础镜像为安装了pm2的node镜像
```
ENV TZ=Asia/Shanghai
WORKDIR /app
COPY . .
RUN npm install && npm run build
EXPOSE 80
CMD [ "pm2-runtime", "start", "pm2.json" ]
```
