### ISSUE TITLE
生成的页面动画不是在滑到页面的时候执行而是载入之后就开始执行

### ISSUE THREAD

**Issue by eroko** [ly525/luban-h5#119]
- [ ] 第一页之后的动画都是在加载之后就直接执行了，而不是滑到那一页的时候执行。
请问这个问题如何解决。
- [x] 还有动画面板里面的动画延迟写成动画类型了。
- [x] 还有编辑界面左上角的0是什么意思？

**Comment by ly525** [comment]
1. 你可以找到所有带动画的元素。使用swiper 的事件，当页面滚动到该页的时候，触发动画即可，欢迎 pr

第二点和第三点 我回头看下，应该是笔误，周末修复下。

**Comment by ly525** [comment]
第二点和第三点，已经修正。
请分别参见：
2. https://github.com/ly525/luban-h5/commit/47bd979edf3ef88e5eaadca319fda6da6f558849
3. https://github.com/ly525/luban-h5/commit/90e6fa6b7c4827753ae4508adb3883448bfd6bc4
