### ISSUE TITLE
feat request: music/音频功能

### ISSUE THREAD

**Issue by JakeWoki** [ly525/luban-h5#122]
希望增加音频播放功能

**Comment by ly525** [comment]
@JakeWoki  预计年前会加上，敬请期待。欢迎多多反馈建议、意见 😄

**Comment by JakeWoki** [comment]
同时增加一些属性：
1、是否当前页面开始播放2、是否离开当前页面暂停播放

**Comment by ly525** [comment]
> 同时增加一些属性：
> 1、是否当前页面开始播放2、是否离开当前页面暂停播放

OK 会考虑添加相关属性配置的
如果有音乐相关配置，直接继续评论即可

**Comment by ly525** [comment]
@JakeWoki 基本的背景音乐已经上线：https://github.com/ly525/luban-h5/releases/tag/v1.7.4
目前来说，比较简单，需要大家先配置音乐的 URL，后续会支持上传音乐和音乐素材库 😄
