### ISSUE TITLE
移动端页面，如果有输入框，focus后，键盘弹起、焦点失去之后，不会恢复

### ISSUE THREAD

**Issue by yirenkeji555** [ly525/luban-h5#137]
![image](https://user-images.githubusercontent.com/48214423/75753584-0f1fa180-5d66-11ea-80b5-b4fe9d2647fa.png)
![image](https://user-images.githubusercontent.com/48214423/75753667-2eb6ca00-5d66-11ea-905d-11df35d30588.png)

**Comment by yirenkeji555** [comment]
![1583221641046](https://user-images.githubusercontent.com/48214423/75753709-48f0a800-5d66-11ea-89a8-459b317e061e.jpg)

**Comment by ly525** [comment]
收到，将在v1.10.2 中修复

**Comment by ly525** [comment]
https://github.com/taylorchen709/vue-chat/issues/2

**Comment by ly525** [comment]
@yirenkeji555 方便提供下 iOS 版本、浏览器环境吗？是在微信里面打开的吗？
