### ISSUE TITLE
加载我的图库的接口403怎么解决

### ISSUE THREAD

**Issue by laozb** [ly525/luban-h5#138]
upload/files?_limit=10&_start=0&mime=image%2Fpng，已经按照文档在admin里配置了，但这个接口还是403，无法查询到已经上传过的图

**Comment by ly525** [comment]
我晚点看看，周末吧。看下admin 配置是不是配置完整了。strapi相关问题可以去 strapi 仓库看看

**Comment by ly525** [comment]
![image](https://user-images.githubusercontent.com/12668546/91663113-6b972a00-eb19-11ea-9692-fa50def1c36b.png)
