### ISSUE TITLE
安装 @luban-h5/plugin-common-props 一直报 404

### ISSUE THREAD

**Issue by fws407296762** [ly525/luban-h5#142]
error Couldn't find package "@luban-h5/plugin-common-props@^0.0.1" required by "@luban-h5/lbc-button@^0.0.3" on the "npm" registry.

**Comment by ly525** [comment]
今晚看一下

**Comment by ly525** [comment]
@fws407296762 拉一下最新的代码，重装依赖再试一下呢？
```js
cd front-end/h5 
rm -rf node_modules
yarn
```
