### ISSUE TITLE
如果我拉一个元素，如果超出了指定范围，能不能就让它的宽度到边框为止?

### ISSUE THREAD

**Issue by HitMeIdiot** [ly525/luban-h5#152]
> ![image](https://user-images.githubusercontent.com/12668546/80058031-b2b55300-855a-11ea-95d6-bc2eebd23272.png)

**Comment by ly525** [comment]
「 HitMeIdiot: 还有一个就是如果我拉一个元素，如果超出了指定范围，能不能就让它的宽度到边框为止 」
- - - - - - - - - - - - - - -
这个其实不太建议，因为有些时候，允许超出范围是为了 能做多屏适配。

我发点文章给你看看：https://h5.bce.baidu.com/docs/ratio#coordinate

> ![image](https://user-images.githubusercontent.com/12668546/80058060-cc569a80-855a-11ea-9add-70da91c5f947.png)


按照现在的模式：如果你超出了，你自己可以拖拽适配，有想超出去的同学，也可以自己拖拽适配
反过来说: 如果我给你做了截断，你觉得OK
但是如果有人他想不截断，这个就不能满足他了

------
「 HitMeIdiot: 可能实际操作不同，我感觉把它超出去怪怪的😂，存在即合理，这个确实没必要改 」
- - - - - - - - - - - - - - -
如果针对这种需求，其实可以配置成：开关。

针对不同公司，或者开发者，可以自行决定是否打开这个开关。
做成渐进式的开发或者使用体验。可以选择是否截断，类似这样
