### ISSUE TITLE
添加新组件，保存预览组价不存在

### ISSUE THREAD

**Issue by DaiXuYQ** [ly525/luban-h5#161]
这是编辑状态
![微信图片_20200515143452](https://user-images.githubusercontent.com/58066734/82019184-5b1d8980-96b9-11ea-8c4b-e2ba10667aba.png)
这是预览状态
![微信图片_20200515143501](https://user-images.githubusercontent.com/58066734/82019229-6e305980-96b9-11ea-8628-c6a9e21a652d.png)
这是保存h5预览状态
![微信图片_20200515143508](https://user-images.githubusercontent.com/58066734/82019257-7ab4b200-96b9-11ea-911e-bc5e510b5a98.png)

**Comment by ly525** [comment]
试试这个：
```
./luban-h5 rebuild_engine
```
