### ISSUE TITLE
编辑页的 Edit&Preview 里的 checkbox 和 radio 的框框看不到

### ISSUE THREAD

**Issue by HitMeIdiot** [ly525/luban-h5#165]
![image](https://user-images.githubusercontent.com/25999585/83395530-0b66ee00-a42d-11ea-9500-2f2984a2bee1.png)
![image](https://user-images.githubusercontent.com/25999585/83395585-23d70880-a42d-11ea-85cd-b0d5a98fb293.png)
解决：lbp-form-radio.js 里的 props 未定义 type 导致的
![image](https://user-images.githubusercontent.com/25999585/83395847-934cf800-a42d-11ea-9ba4-a1fa9223c7f5.png)

**Comment by ly525** [comment]
感谢，反馈，是否考虑提一个 pr？

**Comment by ly525** [comment]
fixed
