### ISSUE TITLE
[Bug Report/Feeback]图片模块拖动会新打开窗口

### ISSUE THREAD

**Issue by weichenzhiyi** [ly525/luban-h5#188]
火狐浏览器下选择图片模块，拖动位置，新开窗口。如图，每拖动一次新开一个窗口。
![image](https://user-images.githubusercontent.com/29937943/84990096-39f7ff00-b177-11ea-8ca5-8563803cb612.png)

**Comment by ly525** [comment]
感谢反馈，端午节看一下。

**Comment by ly525** [comment]
@weichenzhiyi  firefox 版本是多少？目前我这边么有复现

方便录个视频，然后作为压缩包，作为附件上传到 issue里面吧，我看下

**Comment by ly525** [comment]
暂时无法复现，先关闭了，欢迎继续反馈
