### ISSUE TITLE
[Bug Report/Feeback] 点击左侧组件，在画布中组件会出现2次

### ISSUE THREAD

**Issue by FateZeros** [ly525/luban-h5#189]
**问题描述**

点击左侧组件，画布中会出现2个重叠的组件，移动组件后会看见。

拖拽组件到画布中，则不会出现2个组件。

**环境描述/版本信息 (请完成如下信息)**

 - OS: Mac
 - Browser: chrome
 - 鲁班线上 Demo

**如何复现**

点击左侧组件一次即可

**预期结果**

点击左侧组件，画布应只加载一次组件

**截图**

<img width="962" alt="test" src="https://user-images.githubusercontent.com/18113191/86421737-af360900-bd0d-11ea-8c12-268ae875fc24.png">

**其它补充内容**
鲁班线上 Demo 预览功能报错了

**Comment by ly525** [comment]
非常感谢您的反馈，👍

**Comment by ly525** [comment]
fixed in 2a3a7df
