### ISSUE TITLE
[Bug Report/Feeback]文字组件、input设置name bug

### ISSUE THREAD

**Issue by whoamis** [ly525/luban-h5#190]
**问题描述**
简明扼要的描述你的问题

文字组件无法输入内容，input名称无法输入只能粘贴

**环境描述/版本信息 (请完成如下信息)**
 - OS: [e.g. Mac/Windows]
 - Node
 - 本地开发版本 or 鲁班线上 Demo?
本地开发版本 和 鲁班线上 Demo都有这种问题

**如何复现**
复现步骤
1.文字组件获取焦点里面内容就会消失,上面的修改颜色功能一些基本不能用
2.input无法输入设置name，可以粘贴设置name
3.
4.

**预期结果**
简明扼要的说明你期待的结果
希望能修复一些bug

**截图**
如果可以的话，附上截图
文字组件获取焦点里面内容就会消失,上面的修改颜色功能一些基本不能用
![image](https://user-images.githubusercontent.com/17946347/86487007-85bdc180-bd8f-11ea-90bc-3cf2a245599d.png)

input无法输入设置name，可以粘贴设置name
![image](https://user-images.githubusercontent.com/17946347/86487083-ba317d80-bd8f-11ea-9e23-40daac4db4c4.png)

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by ly525** [comment]
收到 感谢反馈，修复中

**Comment by ly525** [comment]
- [x] input无法输入设置name，可以粘贴设置name
- [x] 文字组件在预览模式，已经设置为不允许编辑

感谢反馈👍
