### ISSUE TITLE
[Bug Report/Feeback]长页保存无效

### ISSUE THREAD

**Issue by kingov** [ly525/luban-h5#193]
长页保存无效
点击"长页面H5" 预览的时候还是翻页模式

**环境描述/版本信息 (请完成如下信息)**
 - OS: [e.g. ]
 - chrome
 - Node 10.14.1
 - 本地开发版本

**如何复现**
复现步骤
1. 拖放元素 , 布局
2. H5类型设置为"长页面H5"
3. 预览
4. 翻页模式 , 长页面没有生效

**预期结果**
想要长页面模式

**Comment by ly525** [comment]
感谢反馈，长页面预览相关问题可以在此 issue 继续反馈
