### ISSUE TITLE
missmatch version of sass

### ISSUE THREAD

**Issue by zt123123** [ly525/luban-h5#194]
the project use the missing version of sass

![image](https://user-images.githubusercontent.com/18349295/87498226-db487700-c689-11ea-88c7-5684da8db77b.png)

the sass's latest version is 1.26.10
![image](https://user-images.githubusercontent.com/18349295/87498383-4003d180-c68a-11ea-858a-eac9d6c6c23c.png)

**Comment by ly525** [comment]
ok i will fix it later

**Comment by zt123123** [comment]
> ok i will fix it later

I have made a pr

**Comment by ly525** [comment]
https://github.com/luban-h5/vue-cli-plugin-lbhc/pull/1
