### ISSUE TITLE
[Bug Report/Feeback]点击事件无效

### ISSUE THREAD

**Issue by zt123123** [ly525/luban-h5#195]
**问题描述**
简明扼要的描述你的问题

自定义组件绑定事件在编辑模式下生效，预览模式下事件无效

**环境描述/版本信息 (请完成如下信息)**
 - OS: Mac
 - Browser chrome
 - Node v10.15.3
 - 本地开发版本 or 鲁班线上 Demo?
基于官方的demo修改

**如何复现**
复现步骤
1. 找到 lbp-button.js
2. 手动添加一个click事件 如 alert('测试')
3.切换到preview模式下可以正常弹框
4.二维码预览的时候  点击没有任何反应

**预期结果**
简明扼要的说明你期待的结果
点击事件生效

**截图**
如果可以的话，附上截图
截图如下
![image](https://user-images.githubusercontent.com/18349295/87517269-35a8fe00-c6b1-11ea-998b-28a472688f4c.png)
preview可以work
![image](https://user-images.githubusercontent.com/18349295/87517330-4b1e2800-c6b1-11ea-9a53-074867d1ed8f.png)
扫码点击无效
![image](https://user-images.githubusercontent.com/18349295/87517441-70ab3180-c6b1-11ea-9362-4386f4af79d1.png)

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by ly525** [comment]
是否重新编译了 预览引擎模块：`./luban-h5 rebuild_engine`

**Comment by ly525** [comment]
长时间未回复，关闭
