### ISSUE TITLE
[Bug Report/Feeback] 预览正常，长页面无法生成页面

### ISSUE THREAD

**Issue by cydirac** [ly525/luban-h5#196]
**问题描述**
简明扼要的描述你的问题
预览正常，但是长页面无法生成网页

**环境描述/版本信息 (请完成如下信息)**
 - OS: [e.g. Mac/Windows] Mac
 - Node
 - 本地开发版本 or 鲁班线上 Demo?

**如何复现**
复现步骤
1. 修改页面类型为长页面，保存
2.预览页面，正常
3.发布，通过二维码扫码，发现问题
4.

**预期结果**
简明扼要的说明你期待的结果

**截图**
如果可以的话，附上截图

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by ly525** [comment]
fixed in #202
