### ISSUE TITLE
[Bug Report/Feeback]图片组件的默认图片地址404啦

### ISSUE THREAD

**Issue by YuArtian** [ly525/luban-h5#211]
**问题描述**
简明扼要的描述你的问题
线上Demo，图片组件的默认图片地址 404

**环境描述/版本信息 (请完成如下信息)**
 - OS: Mac
 - Browser chrome
 - Node
 - 鲁班线上 Demo

**如何复现**
复现步骤
1. 使用图片组件

**预期结果**
简明扼要的说明你期待的结果

**截图**
如果可以的话，附上截图
![image](https://user-images.githubusercontent.com/16103819/89155605-b9ad2200-d59b-11ea-9dc4-3239cf0f58c4.png)

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by ly525** [comment]
收到

**Comment by ly525** [comment]
fixed，更新了下服务器的 nginx 配置
- 注释了默认的图片相关 nginx 配置
- H5作品中的图片 -> `strapi.router.get('/*', koaStatic(path.resolve('./build-editor')));`
- admin 管理后台走 -> strapi public asset 配置：https://strapi.io/documentation/v3.x/concepts/public-assets.html#public-assets

```nginx
server
{
    # location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    # {
    #     expires      30d;
    #     error_log off;
    #     access_log /dev/null;
    # }

    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/h5.luban-h5.com.conf;
    #REWRITE-END
    location / {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass http://localhost:1337;
    }
}
```
