### ISSUE TITLE
[Bug Report/Feeback]长页面H5配置问题

### ISSUE THREAD

**Issue by bulabulabua** [ly525/luban-h5#213]
**问题描述**
在配置长页面时，如果先把操作面板的高度拉高，再从组件面板拖组件进行配置时，预览/保存页面内容不生效（即：配好的组件没有被存起来）

**环境描述/版本信息 (请完成如下信息)**
 - OS: mac
 - Browser chrome
 - Node
 - 鲁班线上 Demo

**如何复现**
复现步骤
1. 创建新作品
2.对中间操作面板高度拉高
3.拖左侧任意组件进行配置
4.预览

**预期结果**
应该显示配好的页面

**Comment by ly525** [comment]
收到，我关注下

**Comment by ly525** [comment]
@bulabulabua 拉下最新代码试试呢？昨天修正了这个问题，另外如果新增了组件，需要执行下  ./luban-h5.sh rebuild_fe
