### ISSUE TITLE
[Bug Report/Feeback] add loading for fetch h5 work templates

### ISSUE THREAD

**Issue by XguangY** [ly525/luban-h5#215]
**问题描述**
取值与所需值不符，导致tips 作品列表获取中 功能失效。修改下就好了

**截图**
如果可以的话，附上截图
![image](https://user-images.githubusercontent.com/31021895/89882982-28245c80-dbfa-11ea-8c3e-f5d96bd3bdb6.png)

**Comment by XguangY** [comment]
@ly525

**Comment by ly525** [comment]
好的 收到，周末修复下，欢迎 pr
