### ISSUE TITLE
[Bug Report/Feeback] 快速部署出现错误！

### ISSUE THREAD

**Issue by 314205221** [ly525/luban-h5#221]
**问题描述**
简明扼要的描述你的问题

![image](https://user-images.githubusercontent.com/57166996/92071887-7cc68c00-ede2-11ea-8e60-98298fe863f4.png)

**环境描述/版本信息 (请完成如下信息)**
 - OS: [e.g. Mac/Windows]
 - Node
 - 本地开发版本 or 鲁班线上 Demo?

**如何复现**
复现步骤
1.
2.
3.
4.

**预期结果**
简明扼要的说明你期待的结果

**截图**
如果可以的话，附上截图

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by ly525** [comment]
@314205221 按照issue 模版提供以下信息（注意提问礼仪！！！）


**环境描述/版本信息 (请完成如下信息)**
 - OS: [e.g. Mac/Windows]
 - Browser [e.g. chrome, safari]
 - Node
 - 本地开发版本 or 鲁班线上 Demo?



**如何复现**
复现步骤
1.
2.
3.
4.

**预期结果**
简明扼要的说明你期待的结果



**截图**
如果可以的话，附上截图



**其它补充内容**
任何和这个问题有关的额外内容
