### ISSUE TITLE
[Bug Report/Feeback]

### ISSUE THREAD

**Issue by sushujuan** [ly525/luban-h5#264]
**问题描述**
文本编辑之后，选中其他element元素为editingElement，文本编辑模式还存在，并且此文本不能选中为editingElement

**环境描述/版本信息 (请完成如下信息)**
 - v1.14.0
 - 本地开发版本 & 鲁班线上 Demo均有

**如何复现**
复现步骤
1.dbclick编辑文本元素
2.点击其他元素

**预期结果**
非文本元素为editingElement时，文本不为编辑模式，并且可重新选中文本为editingElement

**截图**
![image](https://user-images.githubusercontent.com/9583256/97153010-c1e8b800-17ac-11eb-90f4-4af99a05bc6e.png)

**Comment by ly525** [comment]
感谢反馈 👍

**Comment by ly525** [comment]
相关方案已经修复上线，还请更新下呢

**Comment by ly525** [comment]
8ca8770fb2c4325552f353000283ce3f6eabfb43
