### ISSUE TITLE
[Bug Report/Feeback]

### ISSUE THREAD

**Issue by 14790392447w** [ly525/luban-h5#269]
**问题描述**
简明扼要的描述你的问题
点击创建新作品，可以进入页面。
页面空白无显示 console 报错 ：
[Vue warn]: Invalid value for option "watch": expected an Object, but got Function
vue.runtime.esm.js?2b0e:619 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Anonymous>
       <Editor> at src/views/Editor.vue
         <App> at src/App.vue
           <Root>

**环境描述/版本信息 (请完成如下信息)**
 - OS: [e.g. Mac/Windows] Windows
 - Browser [e.g. chrome, safari] chrome
 - Node 12.19.0
 - 本地开发版本

**如何复现**
复现步骤
1.
2.
3.
4.

**预期结果**
简明扼要的说明你期待的结果

**截图**
如果可以的话，附上截图
![image](https://user-images.githubusercontent.com/49028226/97686973-6aac5580-1ad4-11eb-800b-c25976f5b31e.png)
![image](https://user-images.githubusercontent.com/49028226/97687072-7435bd80-1ad4-11eb-9c37-9715c7ec2462.png)

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by ly525** [comment]
问题还在吗？
