### ISSUE TITLE
### 如何在多属性自定义编辑器里监听具体某个操作

### ISSUE THREAD

**Issue by cYouPeng** [ly525/luban-h5#272]
**问题描述**
在画布上，我选择了一段文本，然后再编辑器里对这段选择的文本操作样式，比如文字大小，斜体，粗体。我需要知道我做了哪些操作，然后才能对这段文本做相应操作

**Comment by ly525** [comment]
文本大小调整、斜体、粗体 这些，我理解 富文本编辑器应该已经实现了吧？

**Comment by ly525** [comment]
sorry 没太听懂你的意思，操作文本可以在富文本编辑器中进行
