### ISSUE TITLE
接口403报错

### ISSUE THREAD

**Issue by sunscheung** [ly525/luban-h5#287]
**接口403报错**
   clone下代码，本地后端和前端分别开启，接口报403错误
```debug GET \works?is_template=false (82 ms) 403```

**环境描述/版本信息 (请完成如下信息)**
 - OS: [Windows]
 - Browser [chrome]
 - Node v10.18.1
 - 本地开发版本  

**如何复现**
复现步骤
1.  cd back-end/h5-api 
    yarn 
    yarn dev
2. cd front-end/h5
   yarn
   yarn build:engine 
   yarn dev
3. 运行报403错误
4. 访问http://localhost:1337/admin/
5. Roles & Permissions --> 权限全部勾选后保存，重新访问前端页面还是403错误。

**预期结果**
希望403问题消除

**截图**
 截图可能看不到
```
API 403 Forbidden
- #!zh: 接口 403
- #!en: API 403 Forbidden
- #!en: solution(#!zh: 解决方案)
- ```
```
[2020-12-24T06:40:23.642Z] debug GET \works?is_template=false (82 ms) 403
[2020-12-24T06:40:25.521Z] debug POST /works (101 ms) 403
[2020-12-24T06:59:38.213Z] debug POST /works (224 ms) 403
[2020-12-24T07:16:20.599Z] debug POST /works (81 ms) 403
[2020-12-24T07:18:28.037Z] debug GET \admin (121 ms) 200
```
![1](https://user-images.githubusercontent.com/9931345/103070204-fb4a7200-45fb-11eb-863e-e2876e0823c1.png)
![3](https://user-images.githubusercontent.com/9931345/103070221-08fff780-45fc-11eb-943f-be196797218d.png)

感谢作者！

**Comment by ly525** [comment]
勾选时候，保存之后，重新执行 yarn dev 试试

**Comment by sunscheung** [comment]
@ly525 
感谢回复。刚才是fork的dev分支有这样的问题。
我重新拉代码，用master分支可以了。走了一遍可以了。
其他看到这个问题的开发者，建议用master分支。

**Comment by ly525** [comment]
好奇问下，为何会clone了 dev分支呢？

**Comment by sendRainAutumn** [comment]
> 勾选时候，保存之后，重新执行 yarn dev 试试

我遇到一样的问题，down的是master分支的代码，也配置了权限，但还是403
