### ISSUE TITLE
在我的作品与模板列表中预览时，点击保存，报错

### ISSUE THREAD

**Issue by javaxiaobei** [ly525/luban-h5#288]
**问题描述**
在我的作品中预览时，点击保存，报错

**环境描述/版本信息 (请完成如下信息)**
 - OS: [e.g. Mac/Windows]
 - windows
 - chrome
 - Node
 - v14.15.2
 - 本地开发版本 or 鲁班线上 Demo?
 - 线上demo

**如何复现**
复现步骤
1.访问线上demo
2.点击我的作品
3.点击预览
4.点击保存
5.出现报错。

**预期结果**
希望在我的作品与模板列表预览时，可以修改标题与描述，点击保存可以保存成功。

**截图**
![微信截图_20201230121556](https://user-images.githubusercontent.com/52097330/103329836-a1352b00-4a99-11eb-85c1-8bc81b04967e.png)

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by ly525** [comment]
@18790252057 有作品ID吗？
