### ISSUE TITLE
[Bug Report/Feeback] 文本（tinymce）的代码没有更新到master分支，请问下什么时候更新到master上啊 

### ISSUE THREAD

**Issue by 407257625** [ly525/luban-h5#302]
**问题描述**
简明扼要的描述你的问题

**环境描述/版本信息 (请完成如下信息)**
 - OS: [e.g. Mac/Windows]
 - Node
 - 本地开发版本 or 鲁班线上 Demo?

**如何复现**
复现步骤
1.
2.
3.
4.

**预期结果**
简明扼要的说明你期待的结果

**截图**
如果可以的话，附上截图

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by ly525** [comment]
b1e09b74337d76cfc7965a4de9262d0fa6bcf236
