### ISSUE TITLE
[Bug Report/Feeback]给组件添加的脚本发布后无效

### ISSUE THREAD

**Issue by thedmj** [ly525/luban-h5#308]
**问题描述**
编辑模式下添加的脚本在预览或者发布（savework）后无效。但是在编辑面板上切换预览是有效果的。另外，使用脚本时页面上会有报错warning.js?2149:7 Warning: [antdv: Each record in table should have a unique `key` prop,or set `rowKey` to an unique primary key.] 。

**环境描述/版本信息 (请完成如下信息)**
 - OS: Mac
 - Browser chrome
 - Node v12
 - 本地开发版本

**如何复现**
复现步骤
1.给普通按钮添加点击事件。
2.点击右上角预览或发布。
3.生成的页面上点击按钮无效。

**截图**
![image](https://user-images.githubusercontent.com/17634075/110745891-ee423400-8276-11eb-9f24-c8e52f58b110.png)

**Comment by ly525** [comment]
收到，我解决下

**Comment by ly525** [comment]
我试了下，线上是可以跳转，你可以制作一个demo，然后贴一下链接吧

我刚才试了下：https://h5.luban-h5.com/#/editor/24108 这个是可以做跳转的
