### ISSUE TITLE
[Feature request/新需求] 希望增加一个复制发布后的页面链接(不带有view_mode参数的)按钮，

### ISSUE THREAD

**Issue by zhangwang945** [ly525/luban-h5#310]
**您的Feature Request/想法是否与已有问题有关? 请描述。**
现在的已发布页面预览时，扫码二维码的链接带有view_mode参数，不友好

**简述你想要的解决方案**
希望增加一个复制发布后的页面链接(不带有view_mode参数的)按钮，

**描述你考虑过的替代方案**
是否有替代方案、你看过的不错的参考方案、交互方案等

**其它补充内容**
任何和这个问题有关的额外内容

**Comment by ly525** [comment]
收到

**Comment by ly525** [comment]
![Uploading image.png…]()

**Comment by ly525** [comment]
![image](https://user-images.githubusercontent.com/12668546/111909848-dac67280-8a99-11eb-8f69-b464947ecc19.png)

**Comment by ly525** [comment]
感兴趣可以帮忙提一个 拷贝到粘贴板的 PR
