### ISSUE TITLE
[Bug Report/Feeback] Integrity check failed for "intl-messageformat-parser"

### ISSUE THREAD

**Issue by yslion** [ly525/luban-h5#394]
**问题描述**
简明扼要的描述你的问题

**环境描述/版本信息 (请完成如下信息)**
 - OS: Windows10 的 Ubuntu子系统
 - Browser  chrome
 - Node  v10.19.0
 - 本地开发版本

yarn install v1.22.17
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
**error https://registry.npm.taobao.org/intl-messageformat-parser/download/intl-messageformat-parser-5.5.1.tgz?cache=0&sync_timestamp=1616944395134&other_urls=https%3A%2F%2Fregistry.npm.taobao.org%2Fintl-messageformat-parser%2Fdownload%2Fintl-messageformat-parser-5.5.1.tgz: Integrity check failed for "intl-messageformat-parser" (computed integrity doesn't match our records, got "sha512-VHu6UWgWLJykaSeI1M2DpZMVRLuGCOV91i5I81xnJuAI0MKHP7ZJ3my5naOQkzG10ris3hBr+o5RElF1wQ5IXA== sha1-2LEGRYeYzNgeedjVLG+X86QSQ1Y=")**
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
root@DESKTOP-8FT8O3B:~/luban-h5#

**Comment by Odinbk** [comment]
同样的问题

yarn install v1.22.10
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error https://registry.npm.taobao.org/intl-messageformat-parser/download/intl-messageformat-parser-5.5.1.tgz?cache=0&sync_timestamp=1616944395134&other_urls=https%3A%2F%2Fregistry.npm.taobao.org%2Fintl-messageformat-parser%2Fdownload%2Fintl-messageformat-parser-5.5.1.tgz: Integrity check failed for "intl-messageformat-parser" (computed integrity doesn't match our records, got "sha512-VHu6UWgWLJykaSeI1M2DpZMVRLuGCOV91i5I81xnJuAI0MKHP7ZJ3my5naOQkzG10ris3hBr+o5RElF1wQ5IXA== sha1-2LEGRYeYzNgeedjVLG+X86QSQ1Y=")
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by qianyu223** [comment]
俺也一样

**Comment by 33YANG** [comment]
后端安装依赖时使用yarn也报这个错，换成npm install可以正常安装

**Comment by KevinBu** [comment]
> 后端安装依赖时使用yarn也报这个错，换成npm install可以正常安装

我用 npm install 安装还是报错：npm ERR! Cannot read properties of null (reading 'pickAlgorithm')

**Comment by denglouhen** [comment]
有解决办法吗？npm install会报错。

**Comment by jtbss** [comment]
cnpm perfectly solves the problem
