### ISSUE TITLE
👨🏻‍💻👩🏻‍💻欢迎加入 鲁班-H5 支持交流群 (#!en: Join Discussion Group)

### ISSUE THREAD

**Issue by ly525** [ly525/luban-h5#57]
扫描二维码加入 [钉钉](https://www.dingtalk.com) 讨论组 或点击 [邀请链接](https://qr.dingtalk.com/action/joingroup?code=v1,k1,ga4PURIUr/kGsO3/LsZbBP3rXosUgjV6IuCmpLsyqds=&_dt_no_comment=1&origin=11) 

#!en: Scan the QR code using [Dingtalk App](https://www.dingtalk.com) to join in Discussion group :

For users in other languages, please keep using Github issue tracker. 🤟

![image](https://user-images.githubusercontent.com/12668546/61447488-a379f700-a983-11e9-9956-139352a2585d.png)

**Comment by ly525** [comment]
![image](https://user-images.githubusercontent.com/12668546/66585418-5cce1e80-ebb9-11e9-91c0-56f658f09e27.png)

**Comment by cheng11231456** [comment]
我想进群

**Comment by dlp-0110** [comment]
怎么进群呀

**Comment by OK-zxl** [comment]
大！ 佬！我！想！进！群！

**Comment by liangshuiying** [comment]
我想进群

**Comment by yangyu5646** [comment]
现在还有新的进群方式吗

**Comment by Mikey-Lucky** [comment]
请问，“上传 PSD，一键转换为 H5”这个增强功能会开放吗，如果开放的话有预计开放的时间吗

**Comment by Dedicatus546** [comment]
这个项目是可以二开商用的吗，我看是 GPL3.0 的协议
