### ISSUE TITLE
关于测试出的一些编辑器的小bug~

### ISSUE THREAD

**Issue by gorkys** [ly525/luban-h5#76]
1. 编辑器缩放可无限制的向下缩放，等于0时，画布消失，小于0时，画布翻转。
2. 编辑器缩放到25%的时候，移动元素会迟缓，越小越迟缓，越大越快速。
3. 编辑器放大后，编辑模式时就无法选中预览模式，预览模式时就无法切换编辑模式
4. 编辑器放大后，右击菜单的位置会存在偏移
5. 对齐辅助线太长，会触发滚动条。

另外，想了解一下关于辅助线的代码在哪里？想参考学习一下。

**Comment by ly525** [comment]
@gorkys 非常感谢你的反馈，👍
编辑器当时没有做约束，是因为在做的时候，确实考虑到了需要设置一个下限值。但没有想好每次缩小、放大的百分比是多少合适，因此暂时就没有设置上下阈值。

最近会加一下，也会参考一些竞品。
关于2、3、4、5 这里面的问题，我来仔细看下

辅助线的代码目前实现的比较简单（最基础的功能😄），我来贴一下具体的代码链接
欢迎围观，给我提供一些意见和建议，后面会着重改进这一点的。
也可以添加一下 Issue 里面的微信群或者钉钉群

https://github.com/ly525/luban-h5/blob/dev/front-end/h5/src/components/core/editor/canvas/edit.js#L109

**Comment by gorkys** [comment]
哈哈哈，因为我改的有一个移动组件，和你这个项目编辑器差不多类型，看到你这个项目后，想着可以把辅助线这个功能移植过去～
有兴趣可以进我仓库看看，最新更新的版本中解决了上面提到的第二个问题～

**Comment by ly525** [comment]
好的  @gorkys 貌似没有到仓库

**Comment by gorkys** [comment]
https://github.com/gorkys/vue-draggable-resizable-gorkys

**Comment by ly525** [comment]
@gorkys 收到，刚才看了下，感觉应该是有很多的学习空间，明天仔细看看。
辅助线，我记得有个组件是专门做这个的，我来找找，之前 star 过貌似

**Comment by ly525** [comment]
@gorkys https://github.com/think2011/ref-line 这个仓库，我的实现还是有些粗糙，推荐这个。从功能来看蛮不错的

**Comment by ly525** [comment]
> https://github.com/gorkys/vue-draggable-resizable-gorkys

冲突检测这个idea 蛮不错的，可以用在长页面制作的场景里面。👍

**Comment by gorkys** [comment]
因为我做过广告机的项目，之前的需求有要求图片元素与视频元素不能重叠，所以做了冲突检测功能(不过用的方法比较笨，应该有很大的优化空间)，磁性吸附的代码借鉴的jq-ui的～目前项目中还在使用，所以想着把辅助线的功能添加进去，更完善一些～
感谢你的推荐，我找时间研究一下～

**Comment by ly525** [comment]
一起学习
