### ISSUE TITLE
试用时遇到的一点小问题特建议

### ISSUE THREAD

**Issue by ownsit** [ly525/luban-h5#81]
1.页面管理中的新增删除页面触发按钮太过隐蔽

**Comment by ly525** [comment]
@ownsit 是的，已经发现了。这个在下个小版本就会改进
会做成和 组件列表同一个级别，会做的的比较明显，让用户尽量第一眼就能看到

可能会改成下面这样（临时方案，到时候参照下优秀案例）
![image](https://user-images.githubusercontent.com/12668546/66619075-2078dd80-ec0e-11e9-8cc1-113ecb6d805a.png)
