### ISSUE TITLE
#!zh前端项目build后没有main目录，部署后，导致404  #!en: build&deploy&visit front-end/h5, 404 error

### ISSUE THREAD

**Issue by initial-desire** [ly525/luban-h5#91]
我这里发现点小问题：
前端项目：npm run build 得到dist，然后发现里面的目录没有main文件夹，导致访问404。然后新建了main把对应文件移进去可以正常访问前端页面了。如果是我个人的问题，请忽略。

----来自不懂前端的后端人员

**Comment by ly525** [comment]
please refer：https://github.com/ly525/luban-h5/commit/4e2e89e311f158c33321d819ac3e14b70e84dbba

**Comment by ly525** [comment]
#!en: because the luban-h5 core app is deployed at `https://domain-for-luban-h5/main/`, so you need to modify the `luban-h5/front-end/h5/vue.config.js` -> `publicPath` according to your domain path

**Comment by ly525** [comment]
@initial-desire 
1. 考虑到使用 main 作为构建的子目录，对开发者不太友好
2. 鲁班后来采用了二级域名来部署，因此暂时不存在 main 的问题了。

请更新代码，nginx 配置由 `location /main` 改为 `location /`

commit：https://github.com/ly525/luban-h5/commit/abfb167
