### ISSUE TITLE
自适应有点问题

### ISSUE THREAD

**Issue by cehui0303** [ly525/luban-h5#94]
头条里看到这个项目第一时间就来看看了，因为我曾经也打算做这么一个东西，类似于易企秀的。做了很多H5的小应用，实在需要这么一个东西。点赞！

**Comment by ly525** [comment]
目前暂时不考虑移动端适配，主要操作是在PC端

**Comment by cehui0303** [comment]
我说的适配是指PC端做出的成果，在移动端上展示效果没有自适应。
